### ISSUE TITLE
Cannot extract files from .7z and .rar (RAR4) archives with unencrypted filenames

### ISSUE THREAD

**Issue by wdDiamant** [microsoft/RecursiveExtractor#125]
When attempting to extract a .7z with unencrypted filenames, i get the following error in the CLI.

2023-03-08 11:20:10.5991|ERROR|Microsoft.CST.RecursiveExtractor.Cli.RecursiveExtractorClient|Exception while extracting. SharpCompress.Common.CryptographicException:Encrypted 7Zip archive has no password specified. (   at SharpCompress.Compressors.LZMA.AesDecoderStream..ctor(Stream input, Byte[] info, IPasswordProvider pass, Int64 limit)
   at SharpCompress.Compressors.LZMA.DecoderRegistry.CreateDecoderStream(CMethodId id, Stream[] inStreams, Byte[] info, IPasswordProvider pass, Int64 limit)
   at SharpCompress.Compressors.LZMA.DecoderStreamHelper.CreateDecoderStream(Stream[] packStreams, Int64[] packSizes, Stream[] outStreams, CFolder folderInfo, Int32 coderIndex, IPasswordProvider pass)

When trying to extract a .rar with unencrypted filenames, i get no error but it just creates a damaged copy of the .rar.

Same issue with the .net standard library variant.

Steps to reproduce:
1. Create a text file.
2. Add it to an .7z archive using 7zip or to an .rar archive using WinRar without checking the Encrypt filenames option.
3. Try to extract the archives using the RecursiveExtractor Tool.

**Comment by gfs** [comment]
Hi @wdDiamant,

I am unable to reproduce this with unencrypted 7z or rar files  with RecursiveExtractor 1.2.10.

**Comment by wdDiamant** [comment]
Hi @gfs,
thanks for the answer. I forgot to mention, that i have this problem with encrypted archives only. Luckily u managed to reproduce the 7z issue i meant. I encountered exactly the same issue with encrypted RAR4 archives with the "Encrypt file names" option disabled. I am using RecursiveExtractor 1.2.10 and WinRar 6.21 to create the RAR4 archive.
